[package]
name = "luwen"
version = "0.6.4"
description = "A high-level interface for safe and efficient access Tenstorrent AI accelerators"
edition = "2021"
license = "Apache-2.0"
authors = [ "Daniel Rosen <drosen@tenstorrent.com>", ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luwen-core = {path = "crates/luwen-core", version="0.2.0"}
luwen-if = {path = "crates/luwen-if", version= "0.6.0" }
luwen-ref = {path = "crates/luwen-ref", version= "0.5.1" }
ttkmd-if = {path = "crates/ttkmd-if", version= "0.2.1" }

serde = {"version" = "1.0.164", features = ["derive"]}
serde_yaml = "0.9.22"
serde_json = "1.0.117"
bincode = "1.3.3"
rand = "0.8.5"
nom = "7.1.3"
clap = {version = "4.4.14", features = ["derive"]}

[package.metadata.workspaces]
independent = true

[workspace]
members = [
    "crates/*",
    "app/*"
]
