[package]
name = "drunken-monkey"
version = "0.0.26"
edition = "2021"

[dependencies]
clap = {version = "4.4.14", features = ["derive"]}

luwen-if = {path = "../../crates/luwen-if", version = "0.0.26" }
luwen-ref = {path = "../../crates/luwen-ref", version = "0.0.26" }
