name: Build All
run-name: Build All
on:
  workflow_dispatch:
  workflow_call:

  #push:
  #  tags: [ 'v*' ]

jobs:
  buildall:
    name: Build All the packages!
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: |
          echo "What started this ref: ${{ github.ref }}"
          echo "What started this sha: ${{ github.sha }}"
          echo "What started this sha: ${{ github.context.sha }}"
  builddeb2204:
    needs:
      - buildall
    name: Build Ubuntu 22.04
    uses: ./.github/workflows/build-deb-ubuntu-22.04.yml
    secrets: inherit
  builddeb2404:
    needs:
      - buildall
    uses: ./.github/workflows/build-deb-ubuntu-24.04.yml
    secrets: inherit
  buildpypi:
    needs:
      - buildall
    uses: ./.github/workflows/build-pypi.yml
    secrets: inherit
