name: Build All
run-name: Build All
on:
  workflow_dispatch:
  workflow_call:

  #push:
  #  tags: [ 'v*' ]

jobs:
  builddeb2204:
      uses: ./.github/workflows/build-deb-ubuntu-22.04.yml
      secrets: inherit
  builddeb2404:
      uses: ./.github/workflows/build-deb-ubuntu-24.04.yml
      secrets: inherit
  buildpypi:
      uses: ./.github/workflows/build-pypi.yml
      secrets: inherit
