name: Build All
run-name: Build All
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        default: ${{ github.ref }}
        required: false
        type: string
      MAJOR:
        required: false
        type: string
      MINOR:
        required: false
        type: string
      PATCH:
        required: false
        type: string
      NUMBER_OF_COMMITS_SINCE_TAG:
        required: false
        type: string

jobs:
  buildall:
    name: Build All the packages!
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: |
          echo "What started this ref: ${{ github.ref }}"
          echo "What started this sha: ${{ github.sha }}"
          echo "Did we get a ref pass in? ${{ inputs.ref }}"
  builddeb2204:
    needs:
      - buildall
    name: Build Ubuntu 22.04
    uses: ./.github/workflows/build-deb-ubuntu-22.04.yml
    with:
      ref: ${{ inputs.ref }}
      MAJOR:  ${{ inputs.MAJOR }}
      MINOR:  ${{ inputs.MINOR }}
      PATCH:  ${{ inputs.PATCH }}
      NUMBER_OF_COMMITS_SINCE_TAG:  ${{ inputs.NUMBER_OF_COMMITS_SINCE_TAG }}
    secrets: inherit
